In [22]:
import tensorflow as tf 
import numpy as np

In [3]:
# Definindo uma constante 

tensor = tf.constant([[23,44] ,[40, 12]])

In [4]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 44],
       [40, 12]], dtype=int32)>

In [5]:
# Definindo uma variável 

var = tf.Variable([[12, 13], [40, 60], [89, 33]])
var

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[12, 13],
       [40, 60],
       [89, 33]], dtype=int32)>

In [6]:
var2 = tf.Variable("Testando texto", dtype="string")

In [7]:
var2

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Testando texto'>

In [8]:
tf.__version__

'2.3.0'

In [9]:
const = tf.constant([[29, 30], [40, 10]])

In [10]:
const

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[29, 30],
       [40, 10]], dtype=int32)>

In [11]:
const.shape

TensorShape([2, 2])

In [15]:
# Acessando o tensor com numpy 
const.numpy()

array([[29, 30],
       [40, 10]], dtype=int32)

In [17]:
# operação com tensores 
const + 4

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[33, 34],
       [44, 14]], dtype=int32)>

In [18]:
tensor = tf.constant([[10, 12], [20, 25]])

In [19]:
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 36],
       [60, 75]], dtype=int32)>

In [23]:
# tensor elevado ao quadrado 
np.square(tensor)

array([[100, 144],
       [400, 625]], dtype=int32)

In [24]:
# raiz quadrada do tensor 
np.sqrt(tensor)

array([[3.16227766, 3.46410162],
       [4.47213595, 5.        ]])

In [26]:
tensor_2 = tf.constant([[20, 11], [58, 23]])

In [27]:
# produto escalar entre dois tensores 
np.dot(tensor, tensor_2)

array([[ 896,  386],
       [1850,  795]], dtype=int32)

In [30]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 12],
       [20, 25]], dtype=int32)>

In [31]:
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 11],
       [58, 23]], dtype=int32)>

In [39]:
# String 
tf_string = tf.constant("TensorFlow String")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow String'>

In [40]:
# tamanho da string
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=17>

In [43]:
# strings com representações numéricas 
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(17,), dtype=int32, numpy=
array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119,  32,  83, 116,
       114, 105, 110, 103], dtype=int32)>

In [46]:
array_strings = tf.constant(["TensorFlow 2.0", "Deep learning", "AI"])

In [47]:
for string in array_strings:
  print(string)

tf.Tensor(b'TensorFlow 2.0', shape=(), dtype=string)
tf.Tensor(b'Deep learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
